consul:
  host: ${{ CONSUL_HOST }}
  port: ${{ CONSUL_PORT }}
  defaults:
    token: ${{CONSUL_TOKEN}}
kong:
  host: ${{ KONG_HOST }}
  port: ${{ KONG_PORT }}
  loopbackEndpoint: ${{ KONG_LOOPBACK_ENDPOINT }}
  secretToken: ${{ KONG_SECRET_TOKEN }}
  upstream:
    name: ${{ SERVICE_NAME }}
service:
  id: ${{ SERVICE_NAME }}
  name: ${{ SERVICE_NAME }}
  port: ${{ SERVER_HTTP_PORT }}
  apiPath: ${{ API_PATH }}
  tags: ["v1.0.1"]
  healthCheck:
    timeout: 10s
    interval: 1s
    route: ${{ API_PATH }}/health
  maxRetry: 10
  retryInterval: 1500
config:
  key: user
  name: user
loadbalance:
  rule: RandomRule
  services:
    - name: user-service
      rule: RoundRobinRule
