import { USER_PERMISSION, USER_GROUP_PERMISSION } from './user';
import { COMPANY_GROUP_PERMISSION, COMPANY_PERMISSION } from './company';
import { FACTORY_GROUP_PERMISSION, FACTORY_PERMISSION } from './factory';
import {
  PERMISSION_USER_GROUP_PERMISSION,
  PERMISSION_USER_PERMISSION,
} from './permission-setting';

export const PERMISSION = [
  ...USER_PERMISSION,
  ...COMPANY_PERMISSION,
  ...FACTORY_PERMISSION,
  ...PERMISSION_USER_PERMISSION,
];

export const GROUP_PERMISSION = [
  USER_GROUP_PERMISSION,
  COMPANY_GROUP_PERMISSION,
  FACTORY_GROUP_PERMISSION,
  PERMISSION_USER_GROUP_PERMISSION,
];

export const INSERT_PERMISSION = {
  permission: PERMISSION,
  groupPermission: GROUP_PERMISSION,
};
